name: release-artifacts

concurrency:
  cancel-in-progress: true

on:
  pull_request:
    branches: [ release, test_artifacts ]

jobs:
  windows-artifacts:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # tag=v3
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: make zlib git 7z
        update: true
    # Based on https://ariya.io/2020/07/on-github-actions-with-msys2
    - name: install mingw gcc
      run: pacman --noconfirm -S gcc
    - name: win64 artifact generation with mingw gcc
      run: >-
        SET "PATH_ORIGINAL=%PATH%" &&
        SET "PATH_MINGW64=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin" &&
        COPY C:\msys64\usr\bin\make.exe C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin\make.exe &&
        SET "PATH=%PATH_MINGW64%;%PATH_ORIGINAL%" &&
        make -v &&
        sh -c "gcc -v" &&
        ECHO Building zlib to static link &&
        SET "CC=gcc" &&
        sh -c "cd .. && git clone --depth 1 --branch v1.2.11 https://github.com/madler/zlib" &&
        sh -c "cd ../zlib && make -f win32/Makefile.gcc libz.a"
        ECHO Building zstd &&
        SET "CPPFLAGS=-I../../zlib" &&
        SET "LDFLAGS=../../zlib/libz.a" &&
        sh -c "make allzstd MOREFLAGS=-static" &&
        ECHO Creating artifacts &&
        ECHO %cd% &&
        lib\dll\example\build_package.bat &&
        make -C programs DEBUGFLAGS= clean zstd &&
        cd programs\ && 7z a -tzip -mx9 zstd-win-binary-%PLATFORM%.zip zstd.exe &&
        appveyor PushArtifact zstd-win-binary-%PLATFORM%.zip &&
        cp zstd.exe ..\bin\zstd.exe &&
        git clone --depth 1 --branch release https://github.com/facebook/zstd &&
        cd zstd &&
        git archive --format=tar release -o zstd-src.tar &&
        ..\zstd -19 zstd-src.tar &&
        appveyor PushArtifact zstd-src.tar.zst &&
        certUtil -hashfile zstd-src.tar.zst SHA256 > zstd-src.tar.zst.sha256.sig &&
        appveyor PushArtifact zstd-src.tar.zst.sha256.sig &&
        cd ..\..\bin\ &&
        7z a -tzip -mx9 zstd-win-release-%PLATFORM%.zip * &&
        appveyor PushArtifact zstd-win-release-%PLATFORM%.zip

      - name: Publish
        uses: skx/github-action-publish-binaries@release-2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: artifacts/*
